version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
      parameters:
  test_results_path:
    default: target/surefire-reports
    description: Specify a custom path for maven test results
    type: string
