orbs:
  maven: circleci/maven@1.0.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test
      - store_test_results:
          path: ~/test-results/MyAPIReports/
  
#   orbs:
#   maven: circleci/maven@1.0.1
# version: 2.1
# workflows:
#   maven_test:
#     jobs:
#      - maven/serenity:aggregate
