orbs:
  maven: circleci/maven@1.0.1
version: 2.1
workflows:
  maven_test:
    jobs:
      build:
        steps:
          - maven/test # checkout, build, test, and upload test results
          - run: mkdir test-reports
          - run: store_test_results
                 path: ~/target/site/serenity
