orbs:
  maven: circleci/maven@3.8.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - store_test_results:
          path: ~/target/site/serenity
